# Generated by Django 4.2 on 2023-11-23 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="tp_fornecedor",
        ),
    ]
