# Generated by Django 4.2 on 2023-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoResiduos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tipo de Resíduo",
                "verbose_name_plural": "Tipos de Resíduos",
                "db_table": "tipo_residuos",
                "ordering": ["nome"],
            },
        ),
    ]
