# Generated by Django 4.2 on 2023-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoResiduos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=20)),
                ("classe", models.CharField(max_length=20)),
                ("unidade_medida", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Tipo de Resíduo",
                "verbose_name_plural": "Tipos de Resíduos",
                "db_table": "tipo_residuos",
                "ordering": ["nome", "classe"],
            },
        ),
    ]
