# Generated by Django 4.2 on 2024-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tipo_residuos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiporesiduos",
            name="nome",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="tiporesiduos",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("Kg", "Kilograma (Kg)"),
                    ("t", "Tonelada (t)"),
                    ("m", "Metro (m)"),
                    ("m²", "Metro Quadrado (m²)"),
                    ("m³", "Metro Cúbico (m³)"),
                    ("L", "Litro (L)"),
                    ("UN", "Unidade (UN)"),
                ],
                max_length=3,
            ),
        ),
    ]
