# fly.toml app configuration file generated for django-gestao-residuos on 2023-05-19T19:30:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-gestao-ambiental"
primary_region = "gru"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
