# Generated by Django 4.2 on 2023-12-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACExtintores",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                (
                    "fonte_emissao",
                    models.CharField(
                        choices=[
                            ("AR CONDICIONADO", "AR CONDICIONADO"),
                            ("EXTINTOR", "EXTINTOR"),
                            ("TRANSFORMADOR", "TRANSFORMADOR"),
                            ("OUTROS", "OUTROS"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "tp_gas",
                    models.CharField(
                        choices=[
                            ("C02", "C02"),
                            ("CH4", "CH4"),
                            ("N20", "N20"),
                            ("R-22", "R-22"),
                            ("R410-A", "R410-A"),
                            ("OUTROS", "OUTROS"),
                        ],
                        max_length=15,
                    ),
                ),
                ("n_unidades", models.IntegerField()),
                (
                    "tp_cadastro",
                    models.CharField(
                        choices=[
                            ("NOVA UNIDADE", "NOVA UNIDADE"),
                            ("RECARGA", "RECARGA"),
                            ("DISPENSA", "DISPENSA"),
                        ],
                        max_length=15,
                    ),
                ),
                ("carga", models.IntegerField(blank=True, default=0)),
                ("capacidade", models.IntegerField(blank=True, default=0)),
                ("recuperacao", models.IntegerField(blank=True, default=0)),
                (
                    "id_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cluster.cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ar Condicionado e Extintores",
                "verbose_name_plural": "Ar Condicionado e Extintores",
                "db_table": "ac_extintores",
                "ordering": ["-id"],
            },
        ),
    ]
