# Generated by Django 4.2 on 2024-01-11 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entrada", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrada",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="entrada",
            old_name="id_entrada",
            new_name="id",
        ),
    ]
