# Generated by Django 4.2 on 2024-01-13 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entrada", "0002_alter_entrada_options_rename_id_entrada_entrada_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrada",
            old_name="peso",
            new_name="valor",
        ),
    ]
