# Generated by Django 4.2 on 2024-02-04 20:04

import json

from django.db import migrations


def read_tp_residuos(apps, schema_editor):
    tp_residuos = apps.get_model("tipo_residuos", "TipoResiduos")
    with open("apps/utils/initial_data/tp_residuos.json") as file:
        data = json.load(file)
        for item in data:
            tp_residuos.objects.create(
                nome=item["fields"]["nome"],
                classe=item["fields"]["classe"],
                unidade_medida=item["fields"]["unidade_medida"],
            )


class Migration(migrations.Migration):
    dependencies = [("tipo_residuos", "0001_initial")]

    operations = [migrations.RunPython(read_tp_residuos)]
