# Generated by Django 4.2 on 2024-02-04 20:17

import json

from django.db import migrations


def read_cidades(apps, schema_editor):
    cidades = apps.get_model("cidades", "Cidades")
    with open("apps/utils/initial_data/cidades.json") as file:
        data = json.load(file)
        for item in data:
            cidades.objects.create(
                nome=item["fields"]["nome"],
                estado=item["fields"]["estado"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [migrations.RunPython(read_cidades)]
