# Generated by Django 4.2 on 2024-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cidades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cidades",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
