# Generated by Django 4.2 on 2024-02-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("destinacao", "0001_initial"),
        ("cluster", "0001_initial"),
        ("tipo_residuos", "0001_initial"),
        ("fornecedor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Saida",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "receita",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "custo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "cdf",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="saida/cdf/"
                    ),
                ),
                (
                    "evidencia",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="saida/evidencia/",
                    ),
                ),
                (
                    "id_cluster",
                    models.ForeignKey(
                        db_column="id_cluster",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cluster.cluster",
                    ),
                ),
                (
                    "id_destinacao",
                    models.ForeignKey(
                        db_column="id_destinacao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="destinacao.destinacao",
                    ),
                ),
                (
                    "id_fornecedor_destinacao",
                    models.ForeignKey(
                        db_column="id_fornecedor_destinacao",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fornecedor_destinacao",
                        to="fornecedor.fornecedor",
                    ),
                ),
                (
                    "id_fornecedor_transporte",
                    models.ForeignKey(
                        db_column="id_fornecedor_transporte",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fornecedor_transporte",
                        to="fornecedor.fornecedor",
                    ),
                ),
                (
                    "id_tp_residuos",
                    models.ForeignKey(
                        db_column="id_tp_residuos",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tipo_residuos.tiporesiduos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saída",
                "verbose_name_plural": "Saídas",
                "db_table": "saida",
                "ordering": ["-id"],
            },
        ),
    ]
