# Generated by Django 4.2 on 2024-01-13 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saida", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saida",
            options={
                "ordering": ["-id"],
                "verbose_name": "Saída",
                "verbose_name_plural": "Saídas",
            },
        ),
        migrations.RenameField(
            model_name="saida",
            old_name="id_saida",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="saida",
            old_name="peso",
            new_name="valor",
        ),
    ]
